theme: jekyll-theme-cayman
title: LinuxAndMore
description: LinuxAndMore Website
author: Nick Hildebrandt
baseurl: ""
url: linuxandmore.github.io
github_username: macandmoreyt
youtube_username: macandmore
